import math
montant=int(input ("Donnez  le montant en Euro : "))
b20=math.floor(montant/20)
r =math.floor(montant%20)
b10=math.floor(r/10)
r=math.floor(r%10)
b5=math.floor(r/5)
r=math.floor(r%5)
p2=math.floor(r/2)
r=math.floor(r%2)
p1=math.floor(r/1)
print("Il y'a",b20," billets de 20 euros")
print(b10," billets de 10 euros")
print(b5," billets de 5 euros")
print(p2," pieces de 2 euros")
print(p1," pieces de 1 euros")
